# Generated by Django 5.1 on 2026-07-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ad title')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='banner image')),
                ('link', models.URLField(blank=True, verbose_name='link URL')),
                ('position', models.CharField(choices=[('hero', 'Hero Slider (Top)'), ('sidebar', 'Sidebar'), ('footer', 'Footer')], default='hero', max_length=20, verbose_name='position')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='rentplay.agency', verbose_name='agency')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['position', 'order', '-created_at'],
            },
        ),
    ]
